---
version: '3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  wordpress:
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db
    image: wordpress
    ports:
      - 8030:80
    restart: always
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/neverending-posts
      - ./test/fixtures/themes/neverending-posts:/var/www/html/wp-content/themes/neverending-posts
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - .mu-plugins:/var/www/html/wp-content/mu-plugins
    working_dir: /var/www/html
  wp:
    image: wordpress:cli
    user: '33:33'
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/neverending-posts
      - ./bin/install-wp.sh:/usr/local/bin/install-wp
      - ./test/fixtures/themes/neverending-posts:/var/www/html/wp-content/themes/neverending-posts
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - .mu-plugins:/var/www/html/wp-content/mu-plugins
    links:
      - db
    command: "--info"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8031:80
    volumes:
      - /sessions
  composer:
    image: composer
    command: install
    working_dir: /var/www/html
    depends_on:
      - wordpress
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - wordpress:/var/www/html
      - ./test/fixtures/themes/neverending-posts:/var/www/html/wp-content/themes/neverending-posts
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - .mu-plugins:/var/www/html/wp-content/mu-plugins
    links:
      - wordpress:wordpress
volumes:
  db_data:
  wordpress:
